### ISSUE TITLE
Which versions to use?

### ISSUE THREAD

**Issue by ebwinter95** [rbouckaert/irreversible#2]
Hi rbouckaert,

I am having a little trouble trying to get the installation instructions working. I have run into some issues and was hoping to get some clarification about:

1) the newest release of BEASTLabs uses java 17 (incompatible with java 8). Given that your instructions suggest using java8, which release of BEASTLabs are you using?

2) Also, when using a compatible java version the ant compiling requires BEASTFX, even when downloaded it continues to produce compiling errors `cannot find symbol`. Makes me wonder if some other releases are incompatible, which release of beast2 are you using? I have tried multiple releases of BEASTLabs with no success.

Thanks for the help!

Best,
Evan

**Comment by rbouckaert** [comment]
Hi Evan, 

Sorry for the confusion: the instructions are for BEAST v2.6. However, since the repository was updated for BEAST v2.7 in the mean time, these instructions no longer work.
Probably easiest to install is to use get BEAST v2.7 from [beast2.org](http://beast2.org), then install the package by hand: in a terminal, go to the BEAST2 package directory (start BEAST v2.7 once to create it).

For BEAST v2.7 the package directory  is ~/.beast/2.7/ for Linux, ~/Library/Application Support/BEAST/2.7/ on OS X, or c:\Users\yourname\BEAST\2.7\ on Windows. Then do:

*    `mkdir irreversible`
*    `cd irreversible`
*    download the latest release (https://github.com/rbouckaert/irreversible/releases/download/v0.0.2/Irreversible.package.v0.0.3.zip) in the `irreversible` directory
*   `unzip Irreversible.package.v0.0.3.zip`

and the package should be installed. Let me know if you get stuck somewhere.

Cheers, Remco

**Comment by ebwinter95** [comment]
Hi Remco, 

Thanks for your quick reply! Forgive me, I am new to working with these sorts of computational tools. I followed the your instructions above and those on the home page detailing running BEAUti, copying the sequences to the example.xml (input4G.xml) file and running it in BEAST, but I am getting an error:
`Exception in thread "Thread-4" java.lang.StackOverflowError
        at java.base/java.util.Collections$UnmodifiableCollection$1.<init>(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableCollection.iterator(Unknown Source)
	at beast.base.evolution.tree.Tree.listNodes(Unknown Source)`

I know that's not much to work with but any troubleshooting advice would be greatly appreciated. 

Best,
Evan
